name: Check Files

on:
  push:
    branches: [main]

jobs:
  check-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check backend files
        run: |
          echo "Checking backend files..."
          ls -la backend/
          ls -la backend/api/
          echo "Backend check completed!"

  check-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check frontend files
        run: |
          echo "Checking frontend files..."
          ls -la frontend/
          echo "Frontend check completed!"

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check docs files
        run: |
          echo "Checking docs files..."
          ls -la docs/
          echo "Docs check completed!"
